name: CI

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'

            - name: Install Playpass CLI
              run: npm install -g playpass

            - name: Playpass login
              run: set PLAYPASS_TOKEN "HuxEo9XNKNFrIBcB5ZjKy5lHdeSvULuH"
            - run: export PLAYPASS_TOKEN=HuxEo9XNKNFrIBcB5ZjKy5lHdeSvULuH
            - run: echo $env:PLAYPASS_TOKEN

            - run: npm ci
            - run: npm test --if-present
            - run: npm install dotenv
            - run: npm run build

            - name: Deploy to live
              env:
                PLAYPASS_TOKEN: ${{ secrets.PLAYPASS_TOKEN }} # Reference the secret token
              if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
              run: npx playpass deploy

            - name: Deploy to branch preview
              env:
                PLAYPASS_TOKEN: ${{ secrets.PLAYPASS_TOKEN }}
              if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
              run: npx playpass deploy --prefix "${GITHUB_REF/refs\/heads\/}"

