name: CI

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'

            - run: npm install
            - run: npm ci
            - run: npm test --if-present
            - run: npm install dotenv-cli
            - run: npm install gh-pages --save-dev
            - run: npm install punycode --save

            - name: Install Playpass CLI
              run: npm install -g playpass

            - name: Set PLAYPASS_TOKEN environment variable
              run: set PLAYPASS_TOKEN=HuxEo9XNKNFrIBcB5ZjKy5lHdeSvULuH
            - run: set %PLAYPASS_TOKEN%=HuxEo9XNKNFrIBcB5ZjKy5lHdeSvULuH
            - run: echo "PLAYPASS_TOKEN=${{ secrets.PLAYPASS_TOKEN }}" >> $GITHUB_ENV
            - run: echo PLAYPASS_TOKEN=HuxEo9XNKNFrIBcB5ZjKy5lHdeSvULuH
            - run: echo %PLAYPASS_TOKEN%

            - name: To Deploy Live
              run: npm run build

