name: CI

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'

            - run: npm install
            - run: npm ci
            - run: npm test --if-present
            - run: npm install dotenv
            - run: npm install gh-pages --save-dev

            - name: Install Playpass CLI
              run: npm install -g playpass

            - name: Set PLAYPASS_TOKEN environment variable
              run: echo "PLAYPASS_TOKEN=HuxEo9XNKNFrIBcB5ZjKy5lHdeSvULuH" >> $GITHUB_ENV

            - run: npm run build

            - name: Deploy to live
              env:
                PLAYPASS_TOKEN: HuxEo9XNKNFrIBcB5ZjKy5lHdeSvULuH # Reference the secret token
              if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
              run: npx playpass deploy

            - name: Deploy to branch preview
              env:
                PLAYPASS_TOKEN: HuxEo9XNKNFrIBcB5ZjKy5lHdeSvULuH
              if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
              run: npx playpass deploy --prefix "${GITHUB_REF/refs\/heads\/}"

