name: CI

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'

            - run: npm install
            - run: npm ci
            - run: npm test --if-present
            - run: npm install dotenv-cli
            - run: npm install gh-pages --save-dev
            - run: npm install punycode

            - name: Install Playpass CLI
              run: npm install -g playpass

            - name: Set PLAYPASS_TOKEN environment variable
              run: echo "PLAYPASS_TOKEN=${{ secrets.PLAYPASS_TOKEN }}" >> $GITHUB_ENV

            - run: npm run build

            - name: Deploy to live
              env:
                PLAYPASS_TOKEN: ${{ secrets.PLAYPASS_TOKEN }}
              if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
              run: dotenv npx playpass deploy

            - name: Deploy to branch preview
              env:
                PLAYPASS_TOKEN: ${{ secrets.PLAYPASS_TOKEN }}
              if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
              run: dotenv npx playpass deploy --prefix "${GITHUB_REF/refs\/heads\/}"

